added comments and readmes
kalenkovich/biomag2020_depression pull request #27
Opened 2021-04-23 13:46 UTC by kalenkovich

2021-04-23 13:49 UTC, kalenkovich commented
@KirStepanovskikh, please take a look at whether the comments/readme's are
- sufficient,
- helpful.

If some things are not clear because there is no comment or the comment is not clear, tell me - I'll fix it. If something is not clear but you know what is happening, you can add/update comments yourself. But in that case, please use suggestions on GitHub (comment under the "Files changed" tab here).

2021-04-28 15:29 UTC, KirStepanovskikh commented on 01_preprocessing/README.MD
> +This code was later translated into a snakemake rule that would be run for each subject.
```suggestion
This code was later translated into a snakemake rule (`make_preproc_report`) that would be run for each subject.   
```

2021-04-28 17:06 UTC, levchenkoegor requested changes

2021-04-28 17:06 UTC, levchenkoegor commented on Snakefile
> +# We don't know how to compare eigenspectra for different sets of sensors and thus will later use only the sesnors that
```suggestion
# We don't know how to compare eigenspectra for different sets of sensors and thus will later use only the sensors that
```

2021-04-30 15:01 UTC, merged